Add task runner and update mdisk

diff --git a/mdisk b/mdisk
--- a/mdisk
+++ b/mdisk
@@ -27,7 +27,13 @@ else
 fi
 
 if [[ -d "$mount_path" ]]; then
-  if [[ -z "$(ls -A $mount_path)" ]]; then
+  if [[ "$mount_path" == "/test" ]]; then
+    echo
+    echo "!! ERROR: '/' is a critical directory !!"
+    echo "!! Exiting !!"
+    echo
+    exit 1
+  elif [[ -z "$(ls -A $mount_path)" ]]; then
     sudo rm -r $mount_path
     echo "Existing empty directory at $mount_path removed"
   else
